/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Defines VT.ApiPlaneraResa.Core.Models.TransportSubMode
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum VTApiPlaneraResaCoreModelsTransportSubMode
    {
        /// <summary>
        /// Enum Unknown for value: unknown
        /// </summary>
        [EnumMember(Value = "unknown")]
        Unknown,

        /// <summary>
        /// Enum None for value: none
        /// </summary>
        [EnumMember(Value = "none")]
        None,

        /// <summary>
        /// Enum Vasttagen for value: vasttagen
        /// </summary>
        [EnumMember(Value = "vasttagen")]
        Vasttagen,

        /// <summary>
        /// Enum Longdistancetrain for value: longdistancetrain
        /// </summary>
        [EnumMember(Value = "longdistancetrain")]
        Longdistancetrain,

        /// <summary>
        /// Enum Regionaltrain for value: regionaltrain
        /// </summary>
        [EnumMember(Value = "regionaltrain")]
        Regionaltrain
    }

}
